# Configuración de la aplicación
quarkus.application.name=ms-rate-service
quarkus.http.port=8080

# Configuración de base de datos PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=banco_user
quarkus.datasource.password=banco_password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/banco_abc
# Configuración de Hibernate
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=no-file
quarkus.hibernate-orm.log.bind-parameters=true

# Configuración del cliente REST para API externa
#API tipo-cambio
quarkus.rest-client.api-proxy.url=https://free.e-api.net.pe
# Configuración de timeout para cliente REST
quarkus.rest-client.api-proxy.connect-timeout=5000
quarkus.rest-client.api-proxy.read-timeout=5000

# Configuración para quarkus-openapi-generator

quarkus.openapi-generator.codegen.spec.tipocambioapi_yml.base-package=com.banco.abc.proxy
quarkus.rest-client.tipocambioapi_yml.api-name-suffix=ExchangeRateClient
quarkus.openapi-generator.validateSpec=true
quarkus.rest-client.tipocambioapi_yml.url=https://free.e-api.net.pe
quarkus.rest-client.tipocambioapi_yml.connect-timeout=5000
quarkus.rest-client.tipocambioapi_yml.read-timeout=5000

# Configuración de TLS
quarkus.tls.trust-all=false
# Configuración de logging
quarkus.log.level=INFO
quarkus.log.category."com.banco.abc".level=DEBUG

# Ruta para el documento OpenAPI
quarkus.smallrye-openapi.path=/openapi.yaml
# Ruta para la interfaz de Swagger UI
quarkus.swagger-ui.path=/swagger-ui

# Configuración de validación
quarkus.hibernate-validator.fail-fast=false

# Configuración de CORS (si es necesario)
quarkus.http.cors.origins=*
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.methods=GET
